### PR TITLE
4 recover from closing websocket

### PR DESCRIPTION
**Pull request by morph027**
start http gateway as goroutine and then proceed to regular listen mode

### CODE REVIEW

**Comment by bertwesarg** [comment]
as the second commit reverts the first, could you squash the two commits into one, to have only this change, which actually fixes the #4?

**Comment by morph027** [comment]
Squashed...it looks like, the modified code runs stable on my local signal-gateway for some time now. It looks like it was introduced by the commit which puts the listener into a goroutine.

**Comment by nanu-c** [comment]
i will merge and update now axolotl based on this, can we somehow introduce versioning?

**Comment by morph027** [comment]
Jip, we should add versioning....

**Pull request merged**
